blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^all/$', views.AllView.as_view(), name='all'),
    url(r'^me/$', views.MeView.as_view(), name='me'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^(?P<pk>\d+)/$', views.BlogView.as_view(), name='detail'),
    url(r'^(?P<category>\w+)/$', views.CategoryView.as_view(), name='category'),
    # if this line exchanges the location with last line, the third line will not map the BlogView correctly.

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=40)
    url = models.CharField(max_length=200)
    create_time = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', args=[self.name])


class Blog(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=40)
    author = models.CharField(max_length=20)
    content = models.TextField()
    summary = models.CharField(max_length=200, default="No Sumaary")
    tags = models.CharField(max_length=200, default="未分类")
    img = models.ImageField(default="")
    create_time = models.DateField(default="2012-01-01")
    views = models.IntegerField(default=0, verbose_name='people who views')

    def __str__(self):
        return self.title

    def get_tags(self):
        tagslist = self.tags.split(',')
        return tagslist

    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.id])

blog/views.py
from django.db.models import Q
from django.views import generic
import logging

from .models import Category, Blog


# Create your views here.
class BaseMixIn(generic.ListView):
    def get_context_data(self, **kwargs):
        context = super(BaseMixIn, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['hotblogs'] = Blog.objects.order_by('-views')[:5]
        return context


class IndexView(BaseMixIn):
    template_name = 'blog/index.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['bloglists'] = Blog.objects.all()
        return context


class AllView(BaseMixIn):
    template_name = 'blog/all.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(AllView, self).get_context_data(**kwargs)
        context['bloglists'] = Blog.objects.all()
        return context


class CategoryView(BaseMixIn):
    template_name = 'blog/all.html'
    model = Category

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        logging.debug('categoryView')
        key = self.kwargs.get('category')
        context['bloglists'] = Blog.objects.filter(category__name=key)
        return context


class BlogView(BaseMixIn, generic.DetailView):
    template_name = 'blog/detail.html'
    model = Blog

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(BlogView, self).get_context_data(**kwargs)
        blogId = self.kwargs.get('pk')
        blog = Blog.objects.get(id=blogId)
        blog.views += 1
        blog.save()
        context['blog'] = blog
        return context


class SearchView(BaseMixIn):
    template_name = 'blog/all.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        key = self.request.GET.get('search')
        context['bloglists'] = Blog.objects.filter(Q(title__icontains = key) | Q(tags__icontains = key))
        return context


class MeView(BaseMixIn):
    template_name = 'blog/me.html'
    model = Blog

blog/templates/blog/all.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div id="allContent" class="col-lg-9 col-md-8">
        {% if categories %}
            <div id="categoryIndex">
                <div id="categoryShow" class="well">
                    {% for category in categories %}
                        <span class="tags"><a href="{% url 'blog:category' category %}">{{ category }}</a> </span>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% if bloglists %}
            {% for blog in bloglists %}
                <div id="blogIndex">
                    <div id="blogShow" class="well">
                    {{ error }}
                        <div class="blogTitle">
                            <span class="label label-danger">{{ blog.tags }}</span>
                            <a href="{% url 'blog:detail' blog.id %}">
                                {{ blog.title }}
                            </a>
                        </div>
                        <div class="blogContent">
                            <img class="blogImg" src="{% static 'images/ubuntu.jpg' %}">
                            <div class="blogText">
                                <span>{{ blog.summary|slice:'150'|safe }}</span>
                            </div>
                        </div>
                        <div class="blogFooter">
{#                            <span class="tags">#}
{#                                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>#}
{#                                暂无#}
{#                            </span>#}
                            <span class="tags">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                {{ blog.views }}
                            </span>
                            <span class="tags">
                                <span class="glyphicon glyphicon-calendar" aria-hidden="true">
                                </span>
                                {{ blog.create_time }}
                            </span>
                            <span class="tags">
                                <span class="glyphicon glyphicon-user" aria-hidden="true">
                                </span>
                                {{ blog.author }}
                            </span>
                            {% for tag in blog.get_tags %}
                                <span class="tags">
                                    <span class="label label-success">
                                        {{ tag }}
                                    </span>
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div id="detail" class="col-lg-9 col-md-8">
    {% if blog %}
        <!-- the location-->
            <ol class="breadcrumb">
                <li><a href="#">Home /</li>
                <li><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></li>
            </ol>
        <div id="blog" class="well">

            <div class="title">
                <span>{{ blog.title }}</span>
            </div>
            <div class="tags">
                <span class="tag">
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                    暂无
                </span>
                <span class="tag">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    {{ blog.views }}
                </span>
                <span class="tag">
                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                    {{ blog.create_time }}
                </span>
                <span class="tag">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    {{ blog.author }}
                </span>
                {% for tag in blog.get_tags %}
                    <span class="tag">
                        <span class="label label-success">
                            {{ tag }}
                        </span>
                    </span>
                {% endfor %}
            </div>
            <div class="content">
                {{ blog.content|safe }}
            </div>
        </div>
        <!-- 多说评论框 start -->
        <!-- 多说评论框 end -->
        <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
        <div class="ds-thread" data-thread-key="{{ blog.id }}" data-title="{{ blog.title }}" data-url="{{ blog.get_absolute_url }}"></div>
        <script type="text/javascript" src="/static/js/duoshuo_comments.js"></script>
        <!-- 多说公共JS代码 end -->
    {% endif %}
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <!-- Index mainContent -->
    <div id="mainContent" class="col-lg-9 col-md-8">
        <!-- 轮播 -->
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="{% static 'images/django-carousel.jpg' %}" alt="...">
                    <div class="carousel-caption">
                        <h3>First</h3>
                        <p>11111111111111</p>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static 'images/linux-carousel.jpg' %}" alt="...">
                    <div class="carousel-caption">
                        <h3>Second</h3>
                        <p>22222222222222</p>
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div id="blogIndex">
            <!-- 首页文章列表展示 Start-->
            {% if bloglists %}
                {% for blog in bloglists %}
                    <div id="blogShow" class="well">
                        <div class="blogTitle">
                            <span class="label label-danger">{{ blog.tags }}</span>
                            <a href="{% url 'blog:detail' blog.id %}"<span>{{ blog.title }}</span></a>
                        </div>
                        <div class="blogContent">
                            <img class="blogImg" src="{% static 'images/ubuntu.jpg' %}">
                            <div class="blogText">
                                <span>{{ blog.summary|slice:"100"|safe }}</span>
                            </div>
                        </div>
                        <div class="blogFooter">
{#                            <span class="tags">#}
{#                                <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>#}
{#                                回复#}
{#                            </span>#}
                            <span class="tags">
                                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                {{ blog.views }}
                            </span>
                            <span class="tags">
                                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                                {{ blog.create_time }}
                            </span>
                            <span class="tags">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                {{ blog.author }}
                            </span>
                            {% for tag in blog.get_tags %}
                                <span class="tags">
                                    <span class="label label-success">
                                        {{ tag }}
                                    </span>
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            <!-- 首页文章列表展示 End-->
        </div>
    </div>
    <!-- End -->

{% endblock %}

blog/templates/blog/me.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<!--EDUCATION DESCRIPTION -->
	<div class="container desc">
		<div class="row">
            <div class="col-lg-2 col-lg-offset-1">
                <h5>INFORMATION</h5>
            </div>
            <div class="col-lg-6">
                <p><t>徐昊</t><br/>
                    <i>Even a small star shines in the darkness.</i>
                </p>
            </div>
            <div class="col-lg-3">
                <p><sm>WANT MORE?</sm><br/>
					<imp><sm>IN PROGRESS</sm></imp>
                </p>
            </div>
            <div class="col-lg-6 col-lg-offset-3">
                <p><t>热爱编程、享受生活</t><br/>
                    Now In Beijing <br/>
                </p>
            </div>
		</div><!--/.row -->
		<br>
		<hr>
	</div><!--/.container -->


	<!--SKILLS DESCRIPTION -->
	<div id="skillswrap">
		<div class="container">
			<div class="row">
					<div class="col-lg-2 col-lg-offset-1">
						<h5>SKILLS</h5>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="javascript" height="130" width="130"></canvas>
						<p>Python</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 50,
										color:"#1abc9c"
									},
									{
										value : 50,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("javascript").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="bootstrap" height="130" width="130"></canvas>
						<p>Bootstrap</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 40,
										color:"#1abc9c"
									},
									{
										value : 60,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("bootstrap").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="wordpress" height="130" width="130"></canvas>
						<p>JavaScript</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 45,
										color:"#1abc9c"
									},
									{
										value : 55,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("wordpress").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>

					<div class="col-lg-3 col-lg-offset-3 centered">
						<canvas id="html" height="130" width="130"></canvas>
						<p>HTML/CSS</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 50,
										color:"#1abc9c"
									},
									{
										value : 50,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("html").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
					<div class="col-lg-3 centered">
						<canvas id="photoshop" height="130" width="130"></canvas>
						<p>Django</p>
						<br>
						<script>
							var doughnutData = [
									{
										value: 70,
										color:"#1abc9c"
									},
									{
										value : 30,
										color : "#ecf0f1"
									}
								];
								var myDoughnut = new Chart(document.getElementById("photoshop").getContext("2d")).Doughnut(doughnutData);
						</script>
					</div>
			</div><!--/.row -->
			<br>
		</div><!--/.container -->
	</div><!--/ #skillswrap -->

{% endblock %}

{% block sidebar %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title>{% block title %}Index {% endblock %}</title>
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.js"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/hao.css' %}">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/Chart.js' %}"></script>
</head>
<body class="hao">
{#<div class="haoHeader">#}
{#    <div>hao 啦啦啦啦啦啦啦</div>#}
{#</div>#}
<!-- navigator start-->
<nav id="haoNav" class="navbar navbar-default">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Hao</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'blog:index' %}">首页 <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'blog:all' %}">全部文章</a></li>
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">技术小报 <span class="caret"></span></a>
          <ul class="dropdown-menu">
              {% if categories %}
                  {% for category in categories %}
                      <li role="separator" class="divider"></li>
                      <li><a href="{% url 'blog:category' category.name %}">{{ category.name }}</a></li>
                  {% endfor %}
              {% endif %}
          </ul>
        </li>
            <li><a href="{% url 'blog:me' %}">关于本人</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#">About Me</a></li>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--navigator end-->
<div id="haoContent" class="container">
    <div class="row">
        {% block content %}
        {% endblock %}

        {% block sidebar %}
        <!-- SideBar Start-->
        <div id="sideBar" class="col-lg-3 col-md-4 hidden-xs">
            <form action="{% url 'blog:search' %}" class="input-group">
                {% csrf_token %}
                <input type="text" name="search" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">Go!</button>
                </span>
            </form>
            <!-- /input-group -->
            <!--标签云Start-->
            <div id="tagcloud">
                <img class="tagcloud" src="{% static 'images/ubuntu2.jpg' %}">
            </div>
            <table id="hotblogs" class="well">
                <tr><th>hot blogs</th></tr>
                {% for blog in hotblogs %}
                    <tr><td>
                        <a href="{% url 'blog:detail' blog.id %}"> {{ blog.title|slice:'10'}}</a>
                        <span id="tags">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                {{ blog.views }}
                            </span>
                    </td></tr>
                {% endfor %}
            </table>
            <!-- End -->
            <!-- 多说最新评论 start -->
            <!-- 多说最新评论 end -->
            <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
            <div class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1" data-show-title="1" data-show-admin="1" data-excerpt-length="70">
                <script type="text/javascript" src="/static/js/duoshuo_hotestcomments.js"></script>
            </div>
            <!-- 多说公共JS代码 end -->
        </div><!-- /.col-lg-6 -->
        {% endblock %}
    </div><!-- /.row -->
</div>
</body>
</html>